### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dpnishant** [synopsys-sig/ATOR-Burp#1]
Hi @kashwathkumar Thank you for this awesome plugin. I haven't used it yet but I have read the medium article and watched the demo on YouTube and it looks pretty promising. 🎉

 I have one feature request, though, that would make this even more awesome. While the UI is great for testing out one-off pentest engagements but in large organizations, security teams might need to create multiple configurations so that they can reuse them later on a per application basis.

I was thinking if would be possible for you create a feature for exporting ATOR configs as JSON/YAML files and then import them later. And be able to import multiple configs which trigger based on applications/url patterns e.g. JSON configs which also include `scope` array of URL patterns that shall indicate which config to use when the requests match a specific pattern i.e. a config may be reused for multiple hosts such as `*.example.com` and another config is useful for `api.example.com/v1/*`. Hope you get the idea. And it would be even better if you can expose this config import/export API via Extender so that other plugins can rely on your plugin to create sophisticated automation. 

Do let me know what you guys think and kudos to both of you for all the hard work. Cheers 🍻

**Comment by kashwathkumar** [comment]
We have addressed this feature in the v2.0 release. Please take a look at it and let us know.
